// apps/admin/src/components/forms/SystemForm.svelte
<script lang="ts">
    import Form from '@components/ui/Form.svelte';
    import PageTitle from '@components/ui/PageTitle.svelte';
    import LinkButton from '@components/ui/LinkButton.svelte';
    import Button from '@components/ui/Button.svelte';
    import TextInput from '@components/ui/TextInput.svelte';
    import Select from '@components/ui/Select.svelte';
    import Modal from '@components/ui/Modal.svelte';
    import FileUpload from '@components/ui/FileUpload.svelte';
    import MultiSelector from '@components/ui/MultiSelector.svelte';
    import MilkdownEditor from '@components/ui/MilkdownCrepeEditor.svelte';
    import { actions } from 'astro:actions';
    import { onMount } from 'svelte';

    interface SystemData {
        id?: number | null;
        name?: string | null;
        slug?: string | null;
    }

    let { systemData }: { systemData?: SystemData} = $props();
    let title = $derived(systemData?.id ? `Editing System ${systemData.name}` : 'Create System');
    let isPending = $state(false);
    let formError: string | null = $state(null);

    async function handleSubmit(e: SubmitEvent) {
        e.preventDefault();
        isPending = true;
        formError = null;

        const formData = new FormData(e.target as HTMLFormElement);
        const result = await actions.systems.upsertSystem(formData);
        if (result.error) {
            formError = result.error.message;
            isPending = false;
        }
        else {
            window.location.href = '/systems';
        }
    }
</script>
<Form id="system-form"onsubmit={handleSubmit}>
    {#if systemData?.id}
        <input type="hidden" name="id" value={systemData.id} />
    {/if}
    <PageTitle title={title} hvalue={1}>
        <Button
            type="submit"
            label={isPending ? "Saving..." : "Save System"}
            additionalClasses={isPending ? "btn-disabled" : "btn-primary"}
            disabled={isPending}
        />
        {#if systemData?.id}
            <Button
                type="button"
                label={isPending ? "Publishing..." : "Publish"}
                additionalClasses={isPending ? "btn-disabled" : "btn-secondary"}
                disabled={isPending}
            />
        {/if}
        <LinkButton href="/systems">Back to Systems</LinkButton>
    </PageTitle>
    {#if formError}
        <div class="error">{formError}</div>
    {/if}
    <TextInput name="systemName" label="System Name" value={systemData?.name||''} required />
</Form>

// apps/admin/src/components/forms/SystemForm.tsx
import { actions } from 'astro:actions';
import { withState } from '@astrojs/react/actions';
import { useActionState, useEffect } from "react";
import TextInput from '@components/TextInput';
import Button from '@components/Button';

function SystemForm({ onSuccess, successUrl }: { onSuccess?: (data: unknown) => void, successUrl?: string }) {
    const [state, action, isPending] = useActionState(
        withState(actions.systems.createSystem),
        { data: undefined, error: undefined } as any
    );

    useEffect(() => {
        if (state?.data) {
            if (onSuccess) {
                onSuccess(state.data);
            }
            if (successUrl) {
                window.location.href = successUrl;
            }
        }
    }, [state, onSuccess, successUrl]);

    return (
        <form action={action} className="gap-2">
            <div className="flex-1">
                <TextInput
                    id="name"
                    name="name"
                    label="System Name"
                    placeholder="Enter system name"
                    error={state.error?.message}
                    maxLength={100}
                    required
                />
            </div>
            <div className="flex items-end py-2">
                <Button
                    type="submit"
                    label={isPending ? 'Creating...' : 'Create'}
                    disabled={isPending}
                    additionalClasses="btn-primary"
                />
            </div>
        </form>
    );
}

export default SystemForm;
